name: Test and Build Application
on: push

jobs:
  test-and-build-android-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt-hotspot"

      - name: Run Android Tests
        run: cd android && ./gradlew test

      - name: Run Android Build
        run: |-
          cd android_app
          ./gradlew build
          cp app/build/outputs/apk/release/app-release-unsigned.apk ../app-release.apk

      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: app-release.apk
          retention-days: 1
